export const stores = [
  { short: "Amersham", full: "The Entertainer Amersham", url: "https://www.thetoyshop.com/store/amersham" },
  { short: "Uxbridge", full: "The Entertainer Uxbridge", url: "https://www.thetoyshop.com/store/uxbridge" },
  { short: "Camberley", full: "The Entertainer Camberley", url: "https://www.thetoyshop.com/store/camberley" },
  { short: "Basingstoke", full: "The Entertainer Basingstoke", url: "https://www.thetoyshop.com/store/basingstoke" },
  { short: "Keynsham", full: "The Entertainer Keynsham", url: "https://www.thetoyshop.com/store/keynsham" },
  { short: "Midsomer Norton", full: "The Entertainer Midsomer Norton", url: "https://www.thetoyshop.com/store/midsomer-norton" },
  { short: "Cardiff", full: "The Entertainer Cardiff", url: "https://www.thetoyshop.com/store/cardiff" },
  { short: "Sutton Coldfield", full: "The Entertainer Sutton Coldfield", url: "https://www.thetoyshop.com/store/sutton-coldfield" },
  { short: "Wolverhampton", full: "The Entertainer Wolverhampton", url: "https://www.thetoyshop.com/store/wolverhampton" },
  { short: "Yeovil", full: "The Entertainer Yeovil", url: "https://www.thetoyshop.com/store/yeovil" },
  { short: "Reading", full: "The Entertainer Reading", url: "https://www.thetoyshop.com/store/reading" },
  { short: "Telford", full: "The Entertainer Telford", url: "https://www.thetoyshop.com/store/telford" },
  { short: "Coliseum", full: "The Entertainer Cheshire Coliseum", url: "https://www.thetoyshop.com/store/coliseum" },
  { short: "Crawley", full: "The Entertainer Crawley", url: "https://www.thetoyshop.com/store/crawley" },
  { short: "Nottingham", full: "The Entertainer Nottingham", url: "https://www.thetoyshop.com/store/nottingham" },
  { short: "Solihull", full: "The Entertainer Solihull", url: "https://www.thetoyshop.com/store/solihull" },
  { short: "Lakeside", full: "The Entertainer Lakeside - Grays", url: "https://www.thetoyshop.com/store/lakeside" },
  { short: "Worcester", full: "The Entertainer Worcester", url: "https://www.thetoyshop.com/store/worcester" },
  { short: "Romford Brewery", full: "The Entertainer Romford Brewery", url: "https://www.thetoyshop.com/store/romford" },
  { short: "Guildford", full: "The Entertainer Guildford", url: "https://www.thetoyshop.com/store/guildford" },
  { short: "Coventry", full: "The Entertainer Coventry", url: "https://www.thetoyshop.com/store/coventry" },
  { short: "Bullring", full: "The Entertainer Birmingham - Bullring", url: "https://www.thetoyshop.com/store/birmingham" },
  { short: "Harlow", full: "The Entertainer Harlow", url: "https://www.thetoyshop.com/store/harlow" },
  { short: "Taunton", full: "The Entertainer Taunton", url: "https://www.thetoyshop.com/store/taunton" },
  { short: "Ipswich", full: "The Entertainer Ipswich", url: "https://www.thetoyshop.com/store/ipswich" },
  { short: "Bristol Cabot Circus", full: "The Entertainer Bristol - Cabot Circus", url: "https://www.thetoyshop.com/store/bristol-cabot-circus" },
  { short: "Derby", full: "The Entertainer Derby", url: "https://www.thetoyshop.com/store/derby" },
  { short: "White City", full: "The Entertainer Westfield London", url: "https://www.thetoyshop.com/store/white-city" },
  { short: "Brighton", full: "The Entertainer Brighton", url: "https://www.thetoyshop.com/store/brighton" },
  { short: "Liverpool One", full: "The Entertainer Liverpool One", url: "https://www.thetoyshop.com/store/liverpool" },
  { short: "Chelmsford", full: "The Entertainer Chelmsford", url: "https://www.thetoyshop.com/store/chelmsford" },
  { short: "Hull", full: "The Entertainer Hull", url: "https://www.thetoyshop.com/store/hull" },
  { short: "Bury", full: "The Entertainer Bury", url: "https://www.thetoyshop.com/store/bury" },
  { short: "Warrington", full: "The Entertainer Warrington", url: "https://www.thetoyshop.com/store/warrington" },
  { short: "Hereford", full: "The Entertainer Hereford", url: "https://www.thetoyshop.com/store/hereford" },
  { short: "Stockport", full: "The Entertainer Stockport", url: "https://www.thetoyshop.com/store/stockport" },
  { short: "Manchester Arndale", full: "The Entertainer Manchester - Arndale", url: "https://www.thetoyshop.com/store/arndale" },
  { short: "Merryhill", full: "The Entertainer Merryhill", url: "https://www.thetoyshop.com/store/merryhill" },
  { short: "Chester", full: "The Entertainer Chester", url: "https://www.thetoyshop.com/store/chester" },
  { short: "Cwmbran", full: "The Entertainer Cwmbran", url: "https://www.thetoyshop.com/store/cwmbran" },
  { short: "Newport, IOW", full: "The Entertainer Newport - Isle of Wight", url: "https://www.thetoyshop.com/store/newport-iow" },
  { short: "Welwyn Garden City", full: "The Entertainer Welwyn Garden City", url: "https://www.thetoyshop.com/store/welwyn-garden-city" },
  { short: "Bluewater", full: "The Entertainer Bluewater - Greenhithe", url: "https://www.thetoyshop.com/store/bluewater" },
  { short: "Stratford", full: "The Entertainer Stratford - Westfield", url: "https://www.thetoyshop.com/store/stratford" },
  { short: "Metro Centre", full: "The Entertainer Gateshead - Metro Centre", url: "https://www.thetoyshop.com/store/metro-centre" },
  { short: "Winchester", full: "The Entertainer Winchester", url: "https://www.thetoyshop.com/store/winchester" },
  { short: "Leicester", full: "The Entertainer Leicester", url: "https://www.thetoyshop.com/store/leicester" },
  { short: "Bromley Lower Mall", full: "The Entertainer Bromley Lower Mall", url: "https://www.thetoyshop.com/store/bromley%20lower%20mall" },
  { short: "Jersey", full: "The Entertainer Jersey", url: "https://www.thetoyshop.com/store/jersey" },
  { short: "Grimsby", full: "The Entertainer Grimsby", url: "https://www.thetoyshop.com/store/grimsby" },
  { short: "Newbury", full: "The Entertainer Newbury", url: "https://www.thetoyshop.com/store/newbury" },
  { short: "Barnsley", full: "The Entertainer Barnsley", url: "https://www.thetoyshop.com/store/barnsley" },
  { short: "Redditch", full: "The Entertainer Redditch", url: "https://www.thetoyshop.com/store/redditch" },
  { short: "Didcot", full: "The Entertainer Didcot", url: "https://www.thetoyshop.com/store/didcot" },
  { short: "Southport", full: "The Entertainer Southport", url: "https://www.thetoyshop.com/store/southport" },
  { short: "Leeds White Rose", full: "The Entertainer Leeds White Rose", url: "https://www.thetoyshop.com/store/leeds" },
  { short: "Lincoln", full: "The Entertainer Lincoln", url: "https://www.thetoyshop.com/store/lincoln" },
  { short: "Bexleyheath", full: "The Entertainer Bexleyheath", url: "https://www.thetoyshop.com/store/bexleyheath" },
  { short: "Middlesbrough", full: "The Entertainer Middlesbrough", url: "https://www.thetoyshop.com/store/middlesbrough" },
  { short: "Lancaster", full: "The Entertainer Lancaster", url: "https://www.thetoyshop.com/store/lancaster" },
  { short: "Sunderland", full: "The Entertainer Sunderland", url: "https://www.thetoyshop.com/store/sunderland" },
  { short: "Peterborough", full: "The Entertainer Peterborough", url: "https://www.thetoyshop.com/store/peterborough" },
  { short: "Leeds Trinity", full: "The Entertainer Leeds Trinity", url: "https://www.thetoyshop.com/store/leeds-trinity" },
  { short: "Witney", full: "The Entertainer Witney", url: "https://www.thetoyshop.com/store/witney" },
  { short: "Whiteley", full: "The Entertainer Whiteley", url: "https://www.thetoyshop.com/store/whiteley" },
  { short: "Leamington Spa", full: "The Entertainer Leamington Spa", url: "https://www.thetoyshop.com/store/leamington-spa" },
  { short: "Plymouth", full: "The Entertainer Plymouth", url: "https://www.thetoyshop.com/store/plymouth" },
  { short: "Shrewsbury", full: "The Entertainer Shrewsbury", url: "https://www.thetoyshop.com/store/shrewsbury" },
  { short: "Livingston", full: "The Entertainer Livingston", url: "https://www.thetoyshop.com/store/livingston" },
  { short: "Woking", full: "The Entertainer Woking", url: "https://www.thetoyshop.com/store/woking" },
  { short: "Banbury", full: "The Entertainer Banbury", url: "https://www.thetoyshop.com/store/banbury" },
  { short: "Norwich", full: "The Entertainer Norwich", url: "https://www.thetoyshop.com/store/norwich" },
  { short: "Colchester", full: "The Entertainer Colchester", url: "https://www.thetoyshop.com/store/colchester" },
  { short: "West Bromwich", full: "The Entertainer West Bromwich", url: "https://www.thetoyshop.com/store/west-bromwich" },
  { short: "Swindon", full: "The Entertainer Swindon", url: "https://www.thetoyshop.com/store/swindon" },
  { short: "St Albans", full: "The Entertainer St Albans", url: "https://www.thetoyshop.com/store/st-albans" },
  { short: "Carlisle", full: "The Entertainer Carlisle", url: "https://www.thetoyshop.com/store/carlisle" },
  { short: "Ashford", full: "The Entertainer Ashford", url: "https://www.thetoyshop.com/store/ashford" },
  { short: "Gloucester", full: "The Entertainer Gloucester", url: "https://www.thetoyshop.com/store/gloucester" },
  { short: "Hemel Hempstead", full: "The Entertainer Hemel Hempstead", url: "https://www.thetoyshop.com/store/hemel-hempstead" },
  { short: "Aylesbury", full: "The Entertainer Aylesbury", url: "https://www.thetoyshop.com/store/aylesbury" },
  { short: "Torquay", full: "The Entertainer Torquay", url: "https://www.thetoyshop.com/store/torquay" },
  { short: "Burnley", full: "The Entertainer Burnley", url: "https://www.thetoyshop.com/store/burnley" },
  { short: "Oldham", full: "The Entertainer Oldham", url: "https://www.thetoyshop.com/store/oldham" },
  { short: "Birkenhead", full: "The Entertainer Birkenhead", url: "https://www.thetoyshop.com/store/birkenhead" },
  { short: "Workington", full: "The Entertainer Workington", url: "https://www.thetoyshop.com/store/workington" },
  { short: "Carmarthen", full: "The Entertainer Carmarthen", url: "https://www.thetoyshop.com/store/carmarthen" },
  { short: "Burton on Trent", full: "The Entertainer Burton Upon Trent", url: "https://www.thetoyshop.com/store/burton-upon-trent" },
  { short: "Newport - South", full: "The Entertainer Newport - Wales", url: "https://www.thetoyshop.com/store/newport" },
  { short: "Beverley", full: "The Entertainer Beverley", url: "https://www.thetoyshop.com/store/beverley" },
  { short: "Bradford", full: "The Entertainer Bradford", url: "https://www.thetoyshop.com/store/bradford" },
  { short: "Altrincham", full: "The Entertainer Altrincham", url: "https://www.thetoyshop.com/store/altrincham" },
  { short: "Eastleigh", full: "The Entertainer Eastleigh", url: "https://www.thetoyshop.com/store/eastleigh" },
  { short: "Lichfield", full: "The Entertainer Lichfield", url: "https://www.thetoyshop.com/store/lichfield" },
  { short: "Basildon", full: "The Entertainer Basildon", url: "https://www.thetoyshop.com/store/basildon" },
  { short: "Dunfermline", full: "The Entertainer Dunfermline", url: "https://www.thetoyshop.com/store/dunfermline" },
  { short: "Blackburn", full: "The Entertainer Blackburn", url: "https://www.thetoyshop.com/store/blackburn" },
  { short: "Bishop's Stortford", full: "The Entertainer Bishops Stortford", url: "https://www.thetoyshop.com/store/bishop-stortford" },
  { short: "Belfast", full: "The Entertainer Belfast", url: "https://www.thetoyshop.com/store/belfast" },
  { short: "St. Johns Liverpool", full: "The Entertainer Liverpool St Johns", url: "https://www.thetoyshop.com/store/liverpool-st-johns" },
  { short: "Meadowhall Sheffield", full: "The Entertainer Sheffield Meadowhall", url: "https://www.thetoyshop.com/store/sheffield-meadowhall" },
  { short: "Silverburn Glasgow", full: "The Entertainer Glasgow Silverburn", url: "https://www.thetoyshop.com/store/glasgow-silverburn" },
  { short: "Bolton", full: "The Entertainer Bolton", url: "https://www.thetoyshop.com/store/bolton" },
  { short: "Cambridge", full: "The Entertainer Cambridge", url: "https://www.thetoyshop.com/store/cambridge" },
  { short: "Truro", full: "The Entertainer Truro", url: "https://www.thetoyshop.com/store/truro" },
  { short: "Northampton", full: "The Entertainer Northampton", url: "https://www.thetoyshop.com/store/northampton" },
  { short: "Bracknell", full: "The Entertainer Bracknell", url: "https://www.thetoyshop.com/store/bracknell" },
  { short: "Yate", full: "The Entertainer Yate", url: "https://www.thetoyshop.com/store/yate" },
  { short: "Inverness", full: "The Entertainer Inverness", url: "https://www.thetoyshop.com/store/inverness" },
  { short: "Corby", full: "The Entertainer Corby", url: "https://www.thetoyshop.com/store/corby" },
  { short: "Stevenage", full: "The Entertainer Stevenage", url: "https://www.thetoyshop.com/store/stevenage" },
  { short: "Walsall", full: "The Entertainer Walsall", url: "https://www.thetoyshop.com/store/walsall" },
  { short: "Cumbernauld", full: "The Entertainer Cumbernauld", url: "https://www.thetoyshop.com/store/cumbernauld" },
  { short: "East Kilbride", full: "The Entertainer East Kilbride", url: "https://www.thetoyshop.com/store/east-kilbride" },
  { short: "Huddersfield", full: "The Entertainer Huddersfield", url: "https://www.thetoyshop.com/store/huddersfield" },
  { short: "Kingston Bentalls", full: "The Entertainer Kingston - Bentalls", url: "https://www.thetoyshop.com/store/kingston-bentalls" },
  { short: "Barnstaple", full: "The Entertainer Barnstaple", url: "https://www.thetoyshop.com/store/barnstaple" },
  { short: "Chatham", full: "The Entertainer Chatham", url: "https://www.thetoyshop.com/store/chatham" },
  { short: "Bournemouth", full: "The Entertainer Bournemouth", url: "https://www.thetoyshop.com/store/bournemouth" },
  { short: "Doncaster", full: "The Entertainer Doncaster", url: "https://www.thetoyshop.com/store/doncaster" },
  { short: "Stirling", full: "The Entertainer Stirling", url: "https://www.thetoyshop.com/store/stirling" },
  { short: "Dover", full: "The Entertainer Dover", url: "https://www.thetoyshop.com/store/dover" },
  { short: "Llandudno", full: "The Entertainer Llandudno", url: "https://www.thetoyshop.com/store/llandudno" },
  { short: "Port Talbot", full: "The Entertainer Port Talbot", url: "https://www.thetoyshop.com/store/port-talbot" },
  { short: "York", full: "The Entertainer York", url: "https://www.thetoyshop.com/store/york" },
  { short: "Chesterfield", full: "The Entertainer Chesterfield", url: "https://www.thetoyshop.com/store/chesterfield" },
  { short: "Braehead", full: "The Entertainer Braehead", url: "https://www.thetoyshop.com/store/braehead" },
  { short: "Northwich", full: "The Entertainer Northwich", url: "https://www.thetoyshop.com/store/northwich" },
  { short: "Douglas IOM", full: "The Entertainer Douglas", url: "https://www.thetoyshop.com/store/douglas" },
  { short: "Hanley", full: "The Entertainer Hanley - Stoke-on-Trent", url: "https://www.thetoyshop.com/store/hanley" },
  { short: "Bromley Upper Mall", full: "The Entertainer Bromley Upper Mall", url: "https://www.thetoyshop.com/store/bromley" },
  { short: "Clydebank", full: "The Entertainer Clydebank", url: "https://www.thetoyshop.com/store/clydebank" },
  { short: "Watford", full: "The Entertainer Watford", url: "https://www.thetoyshop.com/store/watford" },
  { short: "Ilford", full: "The Entertainer Ilford", url: "https://www.thetoyshop.com/store/ilford" },
  { short: "Antrim", full: "The Entertainer Antrim", url: "https://www.thetoyshop.com/store/antrim" },
  { short: "Chichester", full: "The Entertainer Chichester", url: "https://www.thetoyshop.com/store/chichester-184" },
  { short: "Chester Broughton Shopping Park", full: "The Entertainer Broughton Park", url: "https://www.thetoyshop.com/store/chester-broughton" },
  { short: "Leeds Spring", full: "The Entertainer Leeds Springs", url: "https://www.thetoyshop.com/store/leeds-springs" },
  { short: "Macclesfield", full: "The Entertainer Macclesfield", url: "https://www.thetoyshop.com/store/macclesfield" },
  { short: "Bath", full: "The Entertainer Bath", url: "https://www.thetoyshop.com/store/bath" },
  { short: "Kings Lynn Vancouver Quarter", full: "The Entertainer King's Lynn Vancouver Quarter", url: "https://www.thetoyshop.com/store/kings-lynn-vancouver" },
  { short: "Bristol Cribbs Causeway", full: "The Entertainer Bristol - Cribbs Causeway", url: "https://www.thetoyshop.com/store/cribbs-causeway-bristol" },
  { short: "St Enoch, Glasgow", full: "The Entertainer Glasgow - St Enoch", url: "https://www.thetoyshop.com/store/st-enoch" },
  { short: "Milton Keynes", full: "The Entertainer Milton Keynes", url: "https://www.thetoyshop.com/store/milton-keynes" },
  { short: "Exeter", full: "The Entertainer Exeter", url: "https://www.thetoyshop.com/store/exeter" },
  { short: "Rushden Lakes", full: "The Entertainer Rushden Lakes", url: "https://www.thetoyshop.com/store/rushden-lakes" },
  { short: "Edinburgh", full: "The Entertainer Edinburgh", url: "https://www.thetoyshop.com/store/edinburgh" },
  { short: "Aberdeen", full: "The Entertainer Aberdeen Union Square", url: "https://www.thetoyshop.com/store/aberdeen" },
  { short: "Dalton Park", full: "The Entertainer Dalton park", url: "https://www.thetoyshop.com/store/dalton-park" },
  { short: "O2", full: "The Entertainer at The O2 London", url: "https://www.thetoyshop.com/store/o2-arena" },
  { short: "Gunwharf Quays", full: "The Entertainer Gunwharf Quays", url: "https://www.thetoyshop.com/store/gunwharf-quays" }
];
